// GENERATED by scripts/generate-archive-room-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const ARCHIVE_ROOM_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 20.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 12.0, kind: "west wall" },
  { x1: 19.0, y1: 0.0, x2: 20.0, y2: 12.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 3.0, y2: 4.0, kind: "preserved sample shelf" },
  { x1: 3.0, y1: 2.0, x2: 5.0, y2: 4.0, kind: "record shelf" },
  { x1: 5.0, y1: 2.0, x2: 7.0, y2: 4.0, kind: "record shelf" },
  { x1: 7.0, y1: 2.0, x2: 9.0, y2: 4.0, kind: "pigeonhole rack" },
  { x1: 9.0, y1: 2.0, x2: 11.0, y2: 4.0, kind: "archive terminal desk" },
  { x1: 11.0, y1: 2.0, x2: 13.0, y2: 4.0, kind: "pigeonhole rack" },
  { x1: 13.0, y1: 2.0, x2: 15.0, y2: 4.0, kind: "sealed record canisters" },
  { x1: 15.0, y1: 2.0, x2: 17.0, y2: 4.0, kind: "record cabinet" },
  { x1: 17.0, y1: 2.0, x2: 19.0, y2: 4.0, kind: "record cabinet" },
  { x1: 1.0, y1: 6.0, x2: 3.0, y2: 8.0, kind: "hearth" },
  { x1: 5.0, y1: 6.0, x2: 9.0, y2: 8.0, kind: "west transcription table" },
  { x1: 11.0, y1: 6.0, x2: 13.0, y2: 8.0, kind: "reading nook table" },
  { x1: 13.0, y1: 6.0, x2: 17.0, y2: 8.0, kind: "east reading table" },
  { x1: 17.0, y1: 6.0, x2: 19.0, y2: 8.0, kind: "sealed record chest" },
  { x1: 1.0, y1: 9.4, x2: 2.0, y2: 10.0, kind: "archive greenery" },
  { x1: 18.0, y1: 9.4, x2: 19.0, y2: 10.0, kind: "archive greenery" },
  { x1: 0.0, y1: 10.0, x2: 20.0, y2: 12.0, kind: "south wall" },
];
