// GENERATED by scripts/generate-canal-print-shop-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const CANAL_PRINT_SHOP_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 20.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 14.0, kind: "west wall" },
  { x1: 19.0, y1: 0.0, x2: 20.0, y2: 14.0, kind: "east wall" },
  { x1: 2.0, y1: 2.0, x2: 4.0, y2: 5.0, kind: "hand press" },
  { x1: 4.0, y1: 3.0, x2: 6.0, y2: 5.0, kind: "printing paper" },
  { x1: 7.0, y1: 3.0, x2: 9.0, y2: 5.0, kind: "compositor's case" },
  { x1: 10.0, y1: 3.0, x2: 12.0, y2: 5.0, kind: "compositor's case" },
  { x1: 13.0, y1: 3.0, x2: 15.0, y2: 5.0, kind: "proof cupboard" },
  { x1: 16.0, y1: 3.0, x2: 18.0, y2: 5.0, kind: "printing paper" },
  { x1: 1.0, y1: 7.0, x2: 3.0, y2: 9.0, kind: "shop stove" },
  { x1: 7.0, y1: 7.0, x2: 9.0, y2: 9.0, kind: "imposing table" },
  { x1: 10.0, y1: 7.0, x2: 12.0, y2: 9.0, kind: "imposing table" },
  { x1: 15.0, y1: 7.0, x2: 17.0, y2: 9.0, kind: "editor's desk" },
  { x1: 2.0, y1: 11.4, x2: 3.0, y2: 12.0, kind: "shop greenery" },
  { x1: 0.0, y1: 12.0, x2: 20.0, y2: 14.0, kind: "south wall" },
];
