// GENERATED by scripts/generate-canal-boarding-house-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const CANAL_BOARDING_HOUSE_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 22.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 14.0, kind: "west wall" },
  { x1: 21.0, y1: 0.0, x2: 22.0, y2: 14.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 3.0, y2: 4.0, kind: "boarder's bed" },
  { x1: 3.0, y1: 2.0, x2: 5.0, y2: 4.0, kind: "boarder's bed" },
  { x1: 5.0, y1: 2.0, x2: 7.0, y2: 4.0, kind: "boarder's bed" },
  { x1: 7.0, y1: 2.0, x2: 8.0, y2: 4.0, kind: "boarder's chest" },
  { x1: 8.0, y1: 2.0, x2: 9.0, y2: 5.0, kind: "alcove partition" },
  { x1: 10.0, y1: 3.0, x2: 12.0, y2: 5.0, kind: "wash tub" },
  { x1: 13.0, y1: 3.0, x2: 15.0, y2: 5.0, kind: "kitchen stove" },
  { x1: 16.0, y1: 3.0, x2: 18.0, y2: 5.0, kind: "crockery dresser" },
  { x1: 19.0, y1: 3.0, x2: 21.0, y2: 5.0, kind: "store cupboard" },
  { x1: 1.0, y1: 7.0, x2: 3.0, y2: 9.0, kind: "settle bench" },
  { x1: 3.0, y1: 7.0, x2: 5.0, y2: 9.0, kind: "corner table" },
  { x1: 6.0, y1: 7.0, x2: 10.0, y2: 9.0, kind: "boarding table" },
  { x1: 11.0, y1: 7.0, x2: 15.0, y2: 9.0, kind: "boarding table" },
  { x1: 18.0, y1: 7.0, x2: 20.0, y2: 9.0, kind: "keeper's counter" },
  { x1: 20.0, y1: 11.4, x2: 21.0, y2: 12.0, kind: "house greenery" },
  { x1: 0.0, y1: 12.0, x2: 22.0, y2: 14.0, kind: "south wall" },
];
