// GENERATED by scripts/generate-caribbean-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const CARIBBEAN_FIELD_BLOCKS = [
  { x1: 29.0, y1: 6.0, x2: 31.0, y2: 8.0, kind: "principal dwelling" },
  { x1: 34.0, y1: 7.0, x2: 36.0, y2: 9.0, kind: "bohio two" },
  { x1: 37.0, y1: 7.4, x2: 38.0, y2: 8.0, kind: "palm" },
  { x1: 25.0, y1: 8.0, x2: 27.0, y2: 10.0, kind: "bohio one" },
  { x1: 31.0, y1: 10.0, x2: 33.0, y2: 12.0, kind: "work canopy" },
  { x1: 37.0, y1: 10.0, x2: 39.0, y2: 12.0, kind: "bohio three" },
  { x1: 8.0, y1: 11.0, x2: 9.0, y2: 12.0, kind: "landed stores" },
  { x1: 24.0, y1: 11.0, x2: 26.0, y2: 13.0, kind: "bohio four" },
  { x1: 7.0, y1: 12.0, x2: 8.0, y2: 13.0, kind: "landed stores" },
  { x1: 8.0, y1: 12.0, x2: 9.0, y2: 13.0, kind: "landed stores" },
  { x1: 16.0, y1: 12.0, x2: 18.0, y2: 13.0, kind: "second canoe" },
  { x1: 20.0, y1: 12.0, x2: 21.0, y2: 14.0, kind: "conuco garden" },
  { x1: 21.0, y1: 12.0, x2: 22.0, y2: 14.0, kind: "conuco garden" },
  { x1: 22.0, y1: 12.0, x2: 23.0, y2: 14.0, kind: "conuco garden" },
  { x1: 23.0, y1: 12.0, x2: 24.0, y2: 14.0, kind: "conuco garden" },
  { x1: 35.0, y1: 12.0, x2: 37.0, y2: 14.0, kind: "drying rack" },
  { x1: 39.0, y1: 12.0, x2: 41.0, y2: 13.0, kind: "village canoe" },
  { x1: 6.0, y1: 13.0, x2: 7.0, y2: 15.0, kind: "ship's boat" },
  { x1: 16.0, y1: 15.4, x2: 17.0, y2: 16.0, kind: "palm" },
  { x1: 31.0, y1: 16.0, x2: 32.0, y2: 17.0, kind: "village fire" },
  { x1: 34.0, y1: 16.4, x2: 35.0, y2: 17.0, kind: "palm" },
  { x1: 10.0, y1: 17.0, x2: 13.0, y2: 19.0, kind: "cartographer table" },
  { x1: 42.0, y1: 17.4, x2: 43.0, y2: 18.0, kind: "palm" },
  { x1: 8.0, y1: 18.4, x2: 9.0, y2: 19.0, kind: "palm" },
  { x1: 48.0, y1: 19.4, x2: 49.0, y2: 20.0, kind: "palm" },
  { x1: 7.0, y1: 21.0, x2: 9.0, y2: 23.0, kind: "beached anchor" },
  { x1: 44.0, y1: 21.0, x2: 45.0, y2: 22.0, kind: "command tent" },
  { x1: 47.0, y1: 22.0, x2: 48.0, y2: 23.0, kind: "second tent" },
  { x1: 11.0, y1: 22.4, x2: 12.0, y2: 23.0, kind: "palm" },
  { x1: 45.0, y1: 23.0, x2: 46.0, y2: 24.0, kind: "camp fire" },
  { x1: 20.0, y1: 23.4, x2: 21.0, y2: 24.0, kind: "palm" },
  { x1: 42.0, y1: 24.0, x2: 43.0, y2: 25.0, kind: "supply crates" },
  { x1: 43.0, y1: 24.0, x2: 44.0, y2: 25.0, kind: "supply crates" },
  { x1: 15.0, y1: 25.4, x2: 16.0, y2: 26.0, kind: "palm" },
  { x1: 31.0, y1: 25.4, x2: 32.0, y2: 26.0, kind: "palm" },
  { x1: 37.0, y1: 26.4, x2: 38.0, y2: 27.0, kind: "palm" },
  { x1: 25.0, y1: 27.4, x2: 26.0, y2: 28.0, kind: "palm" },
  { x1: 23.0, y1: 30.0, x2: 25.0, y2: 32.0, kind: "boulders" },
  { x1: 19.0, y1: 30.4, x2: 20.0, y2: 31.0, kind: "palm" },
  { x1: 26.0, y1: 30.4, x2: 27.0, y2: 31.0, kind: "palm" },
];

// The cell each building is entered from — below the centre of its front row.
// Every one of these must have road within reach; see the test named above.
export const CARIBBEAN_FIELD_DOORS = [
  { col: 30, row: 8 },
  { col: 35, row: 9 },
  { col: 26, row: 10 },
  { col: 32, row: 12 },
  { col: 38, row: 12 },
  { col: 25, row: 13 },
  { col: 21, row: 14 },
  { col: 36, row: 14 },
  { col: 11, row: 19 },
  { col: 44, row: 22 },
  { col: 47, row: 23 },
];
