// GENERATED by scripts/generate-fairmeadow-building-and-loan-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const FAIRMEADOW_BUILDING_AND_LOAN_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 16.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 14.0, kind: "west wall" },
  { x1: 15.0, y1: 0.0, x2: 16.0, y2: 14.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 4.0, y2: 4.0, kind: "bound mortgage ledgers" },
  { x1: 6.0, y1: 2.0, x2: 8.0, y2: 4.0, kind: "the mortgage officer's desk" },
  { x1: 8.0, y1: 2.0, x2: 9.0, y2: 3.0, kind: "the association's safe" },
  { x1: 9.0, y1: 2.0, x2: 11.0, y2: 4.0, kind: "bound share ledgers" },
  { x1: 14.0, y1: 2.0, x2: 15.0, y2: 4.0, kind: "the office clock" },
  { x1: 7.0, y1: 4.0, x2: 8.0, y2: 6.0, kind: "the officer's chair" },
  { x1: 1.0, y1: 6.0, x2: 5.0, y2: 8.0, kind: "the counter" },
  { x1: 9.0, y1: 6.0, x2: 13.0, y2: 8.0, kind: "the counter" },
  { x1: 13.0, y1: 6.0, x2: 15.0, y2: 8.0, kind: "the press cupboard" },
  { x1: 1.0, y1: 8.0, x2: 3.0, y2: 10.0, kind: "the writing slope" },
  { x1: 14.0, y1: 8.0, x2: 15.0, y2: 10.0, kind: "a chair" },
  { x1: 1.0, y1: 10.0, x2: 2.0, y2: 12.0, kind: "a chair" },
  { x1: 12.0, y1: 10.0, x2: 14.0, y2: 12.0, kind: "the writing slope" },
  { x1: 14.0, y1: 10.0, x2: 15.0, y2: 12.0, kind: "a chair" },
  { x1: 0.0, y1: 12.0, x2: 16.0, y2: 14.0, kind: "south wall" },
];
