// GENERATED by scripts/generate-fairmeadow-model-house-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const FAIRMEADOW_MODEL_HOUSE_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 20.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 16.0, kind: "west wall" },
  { x1: 19.0, y1: 0.0, x2: 20.0, y2: 16.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 2.0, y2: 3.0, kind: "nightstand" },
  { x1: 2.0, y1: 2.0, x2: 4.0, y2: 4.0, kind: "the double bed" },
  { x1: 4.0, y1: 2.0, x2: 5.0, y2: 3.0, kind: "nightstand" },
  { x1: 5.0, y1: 2.0, x2: 6.0, y2: 4.0, kind: "wardrobe" },
  { x1: 6.0, y1: 2.0, x2: 7.0, y2: 4.0, kind: "wardrobe" },
  { x1: 7.0, y1: 2.0, x2: 8.0, y2: 7.0, kind: "partition" },
  { x1: 8.0, y1: 2.0, x2: 9.0, y2: 4.0, kind: "a single bed" },
  { x1: 9.0, y1: 2.0, x2: 10.0, y2: 3.0, kind: "nightstand" },
  { x1: 10.0, y1: 2.0, x2: 11.0, y2: 4.0, kind: "wardrobe" },
  { x1: 11.0, y1: 2.0, x2: 12.0, y2: 4.0, kind: "wardrobe" },
  { x1: 12.0, y1: 2.0, x2: 13.0, y2: 7.0, kind: "partition" },
  { x1: 13.0, y1: 2.0, x2: 14.0, y2: 4.0, kind: "the bathroom" },
  { x1: 14.0, y1: 2.0, x2: 15.0, y2: 4.0, kind: "the bathroom" },
  { x1: 16.0, y1: 2.0, x2: 17.0, y2: 7.0, kind: "partition" },
  { x1: 17.0, y1: 2.0, x2: 18.0, y2: 4.0, kind: "a single bed" },
  { x1: 18.0, y1: 2.0, x2: 19.0, y2: 4.0, kind: "a wardrobe" },
  { x1: 1.0, y1: 5.0, x2: 3.0, y2: 6.0, kind: "a side table" },
  { x1: 13.0, y1: 5.0, x2: 15.0, y2: 7.0, kind: "the bathroom" },
  { x1: 17.0, y1: 5.0, x2: 18.0, y2: 7.0, kind: "open shelving" },
  { x1: 1.0, y1: 7.0, x2: 4.0, y2: 8.0, kind: "partition" },
  { x1: 5.0, y1: 7.0, x2: 9.0, y2: 8.0, kind: "partition" },
  { x1: 11.0, y1: 7.0, x2: 15.0, y2: 8.0, kind: "partition" },
  { x1: 16.0, y1: 7.0, x2: 18.0, y2: 8.0, kind: "partition" },
  { x1: 1.0, y1: 8.0, x2: 3.0, y2: 9.0, kind: "a hall bench" },
  { x1: 16.0, y1: 8.0, x2: 18.0, y2: 9.0, kind: "a hall bench" },
  { x1: 1.0, y1: 10.0, x2: 5.0, y2: 12.0, kind: "wall cabinets" },
  { x1: 15.0, y1: 10.0, x2: 17.0, y2: 11.0, kind: "the sofa" },
  { x1: 18.0, y1: 10.0, x2: 19.0, y2: 12.0, kind: "a bookcase" },
  { x1: 6.0, y1: 11.0, x2: 8.0, y2: 13.0, kind: "the dinette table" },
  { x1: 11.0, y1: 11.0, x2: 13.0, y2: 13.0, kind: "the card table" },
  { x1: 14.0, y1: 11.0, x2: 15.0, y2: 12.0, kind: "an armchair" },
  { x1: 17.0, y1: 11.0, x2: 18.0, y2: 12.0, kind: "an armchair" },
  { x1: 1.0, y1: 12.0, x2: 2.0, y2: 14.0, kind: "the electric range" },
  { x1: 2.0, y1: 12.0, x2: 3.0, y2: 14.0, kind: "the sink" },
  { x1: 3.0, y1: 12.0, x2: 4.0, y2: 14.0, kind: "the refrigerator" },
  { x1: 14.0, y1: 12.0, x2: 16.0, y2: 13.0, kind: "the coffee table" },
  { x1: 18.0, y1: 12.0, x2: 19.0, y2: 14.0, kind: "a potted palm" },
  { x1: 6.0, y1: 13.0, x2: 8.0, y2: 14.0, kind: "a bench" },
  { x1: 17.0, y1: 13.0, x2: 18.0, y2: 14.0, kind: "a stool" },
  { x1: 0.0, y1: 14.0, x2: 20.0, y2: 16.0, kind: "south wall" },
];
