// GENERATED by scripts/generate-immigrant-port-inspection-hall-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const IMMIGRANT_PORT_INSPECTION_HALL_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 22.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 18.0, kind: "west wall" },
  { x1: 21.0, y1: 0.0, x2: 22.0, y2: 18.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 3.0, y2: 4.0, kind: "filed manifest sheets" },
  { x1: 3.0, y1: 2.0, x2: 7.0, y2: 4.0, kind: "registry desk" },
  { x1: 8.0, y1: 2.0, x2: 12.0, y2: 4.0, kind: "registry desk" },
  { x1: 13.0, y1: 2.0, x2: 14.0, y2: 4.0, kind: "the hall clock" },
  { x1: 15.0, y1: 2.0, x2: 17.0, y2: 4.0, kind: "money exchange counter" },
  { x1: 18.0, y1: 3.0, x2: 19.0, y2: 4.0, kind: "the day's head tax" },
  { x1: 3.0, y1: 7.4, x2: 5.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 5.0, y1: 7.4, x2: 7.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 7.0, y1: 7.4, x2: 9.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 9.0, y1: 7.4, x2: 11.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 11.0, y1: 7.4, x2: 13.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 13.0, y1: 7.4, x2: 15.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 15.0, y1: 7.4, x2: 17.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 17.0, y1: 7.4, x2: 19.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 19.0, y1: 7.4, x2: 21.0, y2: 8.0, kind: "registry floor rail" },
  { x1: 1.0, y1: 11.4, x2: 3.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 3.0, y1: 11.4, x2: 5.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 5.0, y1: 11.4, x2: 7.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 7.0, y1: 11.4, x2: 9.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 9.0, y1: 11.4, x2: 11.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 11.0, y1: 11.4, x2: 13.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 13.0, y1: 11.4, x2: 15.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 15.0, y1: 11.4, x2: 17.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 17.0, y1: 11.4, x2: 19.0, y2: 12.0, kind: "registry floor rail" },
  { x1: 1.0, y1: 12.0, x2: 3.0, y2: 14.0, kind: "waiting bench" },
  { x1: 1.0, y1: 14.0, x2: 3.0, y2: 16.0, kind: "waiting bench" },
  { x1: 4.0, y1: 14.0, x2: 6.0, y2: 16.0, kind: "passengers' luggage" },
  { x1: 0.0, y1: 16.0, x2: 22.0, y2: 18.0, kind: "south wall" },
];
