// GENERATED by scripts/generate-railhead-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const RAILHEAD_FIELD_BLOCKS = [
  { x1: 7.0, y1: 4.4, x2: 11.0, y2: 5.0, kind: "creek cottonwood" },
  { x1: 42.0, y1: 5.0, x2: 44.0, y2: 7.0, kind: "claim cabin" },
  { x1: 7.0, y1: 7.4, x2: 9.0, y2: 8.0, kind: "creek cottonwood" },
  { x1: 42.0, y1: 8.0, x2: 44.0, y2: 10.0, kind: "well" },
  { x1: 13.0, y1: 10.0, x2: 15.0, y2: 12.0, kind: "boarding house" },
  { x1: 18.0, y1: 10.0, x2: 20.0, y2: 12.0, kind: "land office" },
  { x1: 22.0, y1: 10.0, x2: 24.0, y2: 12.0, kind: "telegraph office" },
  { x1: 27.0, y1: 10.0, x2: 29.0, y2: 12.0, kind: "town-site office" },
  { x1: 32.0, y1: 10.0, x2: 34.0, y2: 12.0, kind: "store" },
  { x1: 37.0, y1: 10.0, x2: 39.0, y2: 12.0, kind: "eating house" },
  { x1: 42.0, y1: 10.0, x2: 44.0, y2: 12.0, kind: "freight agent's office" },
  { x1: 45.0, y1: 10.0, x2: 47.0, y2: 11.0, kind: "claim fence" },
  { x1: 47.0, y1: 10.0, x2: 49.0, y2: 11.0, kind: "claim fence" },
  { x1: 51.0, y1: 10.0, x2: 53.0, y2: 11.0, kind: "claim fence" },
  { x1: 40.0, y1: 12.0, x2: 41.0, y2: 14.0, kind: "barrels" },
  { x1: 15.0, y1: 13.0, x2: 17.0, y2: 15.0, kind: "freight wagon" },
  { x1: 19.0, y1: 13.0, x2: 21.0, y2: 14.0, kind: "notice board" },
  { x1: 12.0, y1: 15.0, x2: 14.0, y2: 17.0, kind: "livery stable" },
  { x1: 16.0, y1: 15.0, x2: 17.0, y2: 17.0, kind: "water tank" },
  { x1: 18.0, y1: 15.0, x2: 19.0, y2: 17.0, kind: "water tank" },
  { x1: 20.0, y1: 15.0, x2: 22.0, y2: 17.0, kind: "section house" },
  { x1: 25.0, y1: 16.0, x2: 29.0, y2: 19.0, kind: "depot" },
  { x1: 33.0, y1: 16.0, x2: 37.0, y2: 18.0, kind: "covered platform" },
  { x1: 17.0, y1: 21.0, x2: 20.0, y2: 23.0, kind: "agency stone hut" },
  { x1: 38.0, y1: 21.0, x2: 40.0, y2: 23.0, kind: "loading chute" },
  { x1: 42.0, y1: 21.0, x2: 44.0, y2: 23.0, kind: "stock pen" },
  { x1: 46.0, y1: 21.0, x2: 48.0, y2: 23.0, kind: "stock pen" },
  { x1: 50.0, y1: 21.0, x2: 52.0, y2: 23.0, kind: "stock barn" },
  { x1: 19.0, y1: 22.0, x2: 22.0, y2: 24.0, kind: "agency stone hut" },
  { x1: 26.0, y1: 22.0, x2: 29.0, y2: 24.0, kind: "graders' tent" },
  { x1: 30.0, y1: 22.0, x2: 33.0, y2: 24.0, kind: "graders' tent" },
  { x1: 34.0, y1: 22.0, x2: 37.0, y2: 24.0, kind: "graders' tent" },
  { x1: 26.0, y1: 26.0, x2: 28.0, y2: 28.0, kind: "grading wagon" },
  { x1: 35.0, y1: 27.0, x2: 37.0, y2: 29.0, kind: "supply wagon" },
  { x1: 38.0, y1: 27.0, x2: 42.0, y2: 29.0, kind: "stock pen" },
  { x1: 44.0, y1: 27.0, x2: 48.0, y2: 29.0, kind: "stock pen" },
  { x1: 9.0, y1: 28.0, x2: 12.0, y2: 30.0, kind: "lodge" },
  { x1: 13.0, y1: 28.0, x2: 16.0, y2: 30.0, kind: "lodge" },
  { x1: 16.0, y1: 28.0, x2: 18.0, y2: 30.0, kind: "drying rack" },
  { x1: 20.0, y1: 28.0, x2: 22.0, y2: 30.0, kind: "hide shed" },
  { x1: 27.0, y1: 28.0, x2: 30.0, y2: 30.0, kind: "graders' tent" },
  { x1: 32.0, y1: 28.0, x2: 35.0, y2: 30.0, kind: "graders' tent" },
  { x1: 23.0, y1: 30.0, x2: 25.0, y2: 31.0, kind: "hide yard fence" },
  { x1: 9.0, y1: 31.0, x2: 12.0, y2: 33.0, kind: "lodge" },
  { x1: 13.0, y1: 31.0, x2: 16.0, y2: 33.0, kind: "lodge" },
  { x1: 16.0, y1: 31.0, x2: 18.0, y2: 33.0, kind: "hide stretcher" },
  { x1: 18.0, y1: 31.0, x2: 20.0, y2: 32.0, kind: "hide yard fence" },
];

// The cell each building is entered from — below the centre of its front row.
// Every one of these must have road within reach; see the test named above.
export const RAILHEAD_FIELD_DOORS = [
  { col: 43, row: 7 },
  { col: 49, row: 11 },
  { col: 14, row: 12 },
  { col: 19, row: 12 },
  { col: 23, row: 12 },
  { col: 28, row: 12 },
  { col: 33, row: 12 },
  { col: 38, row: 12 },
  { col: 43, row: 12 },
  { col: 13, row: 17 },
  { col: 21, row: 17 },
  { col: 27, row: 19 },
  { col: 51, row: 23 },
  { col: 21, row: 30 },
];

// Every cell the road network owns — the authored trunk plus the spurs the router
// laid to each door. Read at runtime by engine/npc-routing.js, which prefers these
// cells so a routed NPC walks the road rather than cutting across the fields.
export const RAILHEAD_FIELD_ROADS = [
  [30, 7], [43, 7], [44, 7], [30, 8], [44, 8], [30, 9], [44, 9], [30, 10],
  [44, 10], [30, 11], [44, 11], [49, 11], [14, 12], [19, 12], [23, 12], [28, 12],
  [30, 12], [33, 12], [38, 12], [43, 12], [44, 12], [49, 12], [13, 13], [14, 13],
  [15, 13], [16, 13], [17, 13], [18, 13], [19, 13], [20, 13], [21, 13], [22, 13],
  [23, 13], [24, 13], [25, 13], [26, 13], [27, 13], [28, 13], [29, 13], [30, 13],
  [31, 13], [32, 13], [33, 13], [34, 13], [35, 13], [36, 13], [37, 13], [38, 13],
  [39, 13], [40, 13], [41, 13], [42, 13], [43, 13], [44, 13], [45, 13], [46, 13],
  [47, 13], [48, 13], [49, 13], [14, 14], [22, 14], [30, 14], [14, 15], [22, 15],
  [30, 15], [14, 16], [22, 16], [30, 16], [13, 17], [14, 17], [21, 17], [22, 17],
  [30, 17], [30, 18], [27, 19], [28, 19], [29, 19], [30, 19], [30, 20], [30, 21],
  [30, 22], [30, 23], [51, 23], [30, 24], [50, 24], [51, 24], [19, 25], [20, 25],
  [21, 25], [22, 25], [23, 25], [24, 25], [25, 25], [26, 25], [27, 25], [28, 25],
  [29, 25], [30, 25], [31, 25], [32, 25], [33, 25], [34, 25], [35, 25], [36, 25],
  [37, 25], [38, 25], [39, 25], [40, 25], [41, 25], [42, 25], [43, 25], [44, 25],
  [45, 25], [46, 25], [47, 25], [48, 25], [49, 25], [50, 25], [22, 26], [22, 27],
  [22, 28], [22, 29], [21, 30], [22, 30],
];
