// GENERATED by scripts/generate-richmond-hospital-ward-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const RICHMOND_HOSPITAL_WARD_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 24.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 14.0, kind: "west wall" },
  { x1: 23.0, y1: 0.0, x2: 24.0, y2: 14.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 2.0, y2: 4.0, kind: "ward cot" },
  { x1: 2.0, y1: 2.0, x2: 3.0, y2: 4.0, kind: "ward cot" },
  { x1: 3.0, y1: 2.0, x2: 4.0, y2: 4.0, kind: "bedside table" },
  { x1: 4.0, y1: 2.0, x2: 5.0, y2: 4.0, kind: "ward cot" },
  { x1: 5.0, y1: 2.0, x2: 6.0, y2: 4.0, kind: "ward cot" },
  { x1: 6.0, y1: 2.0, x2: 7.0, y2: 4.0, kind: "bedside table" },
  { x1: 7.0, y1: 2.0, x2: 8.0, y2: 4.0, kind: "ward cot" },
  { x1: 8.0, y1: 2.0, x2: 9.0, y2: 4.0, kind: "ward cot" },
  { x1: 9.0, y1: 2.0, x2: 10.0, y2: 4.0, kind: "bedside table" },
  { x1: 10.0, y1: 2.0, x2: 11.0, y2: 4.0, kind: "ward cot" },
  { x1: 11.0, y1: 2.0, x2: 12.0, y2: 4.0, kind: "ward cot" },
  { x1: 12.0, y1: 2.0, x2: 13.0, y2: 4.0, kind: "bedside table" },
  { x1: 13.0, y1: 2.0, x2: 14.0, y2: 4.0, kind: "ward cot" },
  { x1: 14.0, y1: 2.0, x2: 15.0, y2: 4.0, kind: "ward cot" },
  { x1: 15.0, y1: 2.0, x2: 16.0, y2: 4.0, kind: "bedside table" },
  { x1: 16.0, y1: 2.0, x2: 17.0, y2: 4.0, kind: "ward cot" },
  { x1: 17.0, y1: 2.0, x2: 18.0, y2: 4.0, kind: "ward cot" },
  { x1: 18.0, y1: 2.0, x2: 19.0, y2: 4.0, kind: "bedside table" },
  { x1: 19.0, y1: 2.0, x2: 20.0, y2: 4.0, kind: "ward cot" },
  { x1: 20.0, y1: 2.0, x2: 21.0, y2: 4.0, kind: "ward cot" },
  { x1: 21.0, y1: 2.0, x2: 22.0, y2: 4.0, kind: "bedside table" },
  { x1: 1.0, y1: 6.0, x2: 3.0, y2: 8.0, kind: "linen press" },
  { x1: 3.0, y1: 6.0, x2: 5.0, y2: 8.0, kind: "medicine cabinet" },
  { x1: 6.0, y1: 6.0, x2: 8.0, y2: 8.0, kind: "ward stores" },
  { x1: 9.0, y1: 6.0, x2: 13.0, y2: 8.0, kind: "ward work table" },
  { x1: 16.0, y1: 6.0, x2: 18.0, y2: 8.0, kind: "the matron's desk" },
  { x1: 19.0, y1: 6.0, x2: 21.0, y2: 8.0, kind: "linen press" },
  { x1: 21.0, y1: 6.0, x2: 23.0, y2: 8.0, kind: "ward shelf" },
  { x1: 1.0, y1: 10.0, x2: 2.0, y2: 12.0, kind: "ward cot" },
  { x1: 2.0, y1: 10.0, x2: 3.0, y2: 12.0, kind: "ward cot" },
  { x1: 3.0, y1: 10.0, x2: 4.0, y2: 12.0, kind: "bedside table" },
  { x1: 4.0, y1: 10.0, x2: 5.0, y2: 12.0, kind: "ward cot" },
  { x1: 5.0, y1: 10.0, x2: 6.0, y2: 12.0, kind: "ward cot" },
  { x1: 6.0, y1: 10.0, x2: 7.0, y2: 12.0, kind: "bedside table" },
  { x1: 7.0, y1: 10.0, x2: 8.0, y2: 12.0, kind: "ward cot" },
  { x1: 8.0, y1: 10.0, x2: 9.0, y2: 12.0, kind: "ward cot" },
  { x1: 9.0, y1: 10.0, x2: 10.0, y2: 12.0, kind: "bedside table" },
  { x1: 16.0, y1: 10.0, x2: 17.0, y2: 12.0, kind: "ward cot" },
  { x1: 17.0, y1: 10.0, x2: 18.0, y2: 12.0, kind: "ward cot" },
  { x1: 18.0, y1: 10.0, x2: 19.0, y2: 12.0, kind: "bedside table" },
  { x1: 19.0, y1: 10.0, x2: 20.0, y2: 12.0, kind: "ward cot" },
  { x1: 20.0, y1: 10.0, x2: 21.0, y2: 12.0, kind: "ward cot" },
  { x1: 21.0, y1: 10.0, x2: 22.0, y2: 12.0, kind: "bedside table" },
  { x1: 0.0, y1: 12.0, x2: 24.0, y2: 14.0, kind: "south wall" },
];
