// GENERATED by scripts/generate-richmond-counting-room-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const RICHMOND_COUNTING_ROOM_BLOCKS = [
  { x1: 0.0, y1: 0.0, x2: 18.0, y2: 2.0, kind: "north wall" },
  { x1: 0.0, y1: 0.0, x2: 1.0, y2: 14.0, kind: "west wall" },
  { x1: 17.0, y1: 0.0, x2: 18.0, y2: 14.0, kind: "east wall" },
  { x1: 1.0, y1: 2.0, x2: 3.0, y2: 4.0, kind: "bound ledgers" },
  { x1: 3.0, y1: 2.0, x2: 6.0, y2: 4.0, kind: "bound ledgers" },
  { x1: 6.0, y1: 2.0, x2: 7.0, y2: 4.0, kind: "longcase clock" },
  { x1: 12.0, y1: 2.0, x2: 14.0, y2: 4.0, kind: "the trader's desk" },
  { x1: 2.0, y1: 7.0, x2: 6.0, y2: 9.0, kind: "the clerks' table" },
  { x1: 8.0, y1: 7.0, x2: 10.0, y2: 9.0, kind: "copying desk" },
  { x1: 12.0, y1: 7.0, x2: 14.0, y2: 9.0, kind: "press cupboard" },
  { x1: 15.0, y1: 7.0, x2: 17.0, y2: 9.0, kind: "side table" },
  { x1: 1.0, y1: 10.0, x2: 2.0, y2: 12.0, kind: "waiting chair" },
  { x1: 2.0, y1: 10.0, x2: 3.0, y2: 12.0, kind: "waiting chair" },
  { x1: 3.0, y1: 10.0, x2: 4.0, y2: 12.0, kind: "waiting chair" },
  { x1: 0.0, y1: 12.0, x2: 18.0, y2: 14.0, kind: "south wall" },
];
