// GENERATED by scripts/generate-riverbend-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const RIVERBEND_FIELD_BLOCKS = [
  { x1: 24.0, y1: 6.0, x2: 28.0, y2: 10.0, kind: "meetinghouse" },
  { x1: 31.0, y1: 6.0, x2: 33.0, y2: 9.0, kind: "dwelling two" },
  { x1: 42.0, y1: 6.0, x2: 44.0, y2: 7.0, kind: "field fence" },
  { x1: 44.0, y1: 6.0, x2: 46.0, y2: 7.0, kind: "field fence" },
  { x1: 48.0, y1: 6.0, x2: 50.0, y2: 7.0, kind: "field fence" },
  { x1: 50.0, y1: 6.0, x2: 52.0, y2: 7.0, kind: "field fence" },
  { x1: 36.0, y1: 9.4, x2: 39.0, y2: 10.0, kind: "shade tree" },
  { x1: 34.0, y1: 11.0, x2: 36.0, y2: 14.0, kind: "dwelling three" },
  { x1: 20.0, y1: 12.0, x2: 22.0, y2: 14.0, kind: "dwelling one" },
  { x1: 28.0, y1: 12.0, x2: 30.0, y2: 14.0, kind: "well" },
  { x1: 42.0, y1: 14.0, x2: 44.0, y2: 15.0, kind: "field fence" },
  { x1: 44.0, y1: 14.0, x2: 46.0, y2: 15.0, kind: "field fence" },
  { x1: 46.0, y1: 14.0, x2: 48.0, y2: 15.0, kind: "field fence" },
  { x1: 48.0, y1: 14.0, x2: 50.0, y2: 15.0, kind: "field fence" },
  { x1: 50.0, y1: 14.0, x2: 52.0, y2: 15.0, kind: "field fence" },
  { x1: 29.0, y1: 15.0, x2: 31.0, y2: 17.0, kind: "dwelling five" },
  { x1: 33.0, y1: 15.0, x2: 35.0, y2: 17.0, kind: "hen house" },
  { x1: 21.0, y1: 16.0, x2: 23.0, y2: 20.0, kind: "dwelling four" },
  { x1: 37.0, y1: 16.0, x2: 40.0, y2: 19.0, kind: "barn" },
  { x1: 12.0, y1: 17.0, x2: 13.0, y2: 18.0, kind: "dockside stores" },
  { x1: 23.0, y1: 18.0, x2: 25.0, y2: 20.0, kind: "cold frame" },
  { x1: 14.0, y1: 19.0, x2: 15.0, y2: 20.0, kind: "dockside stores" },
  { x1: 15.0, y1: 19.0, x2: 16.0, y2: 20.0, kind: "dockside stores" },
  { x1: 18.0, y1: 19.0, x2: 20.0, y2: 21.0, kind: "wharf market stall" },
  { x1: 16.0, y1: 20.0, x2: 17.0, y2: 21.0, kind: "dockside stores" },
  { x1: 39.0, y1: 20.0, x2: 40.0, y2: 21.0, kind: "farm stores" },
  { x1: 43.0, y1: 20.0, x2: 44.0, y2: 21.0, kind: "farm stores" },
  { x1: 16.0, y1: 21.0, x2: 18.0, y2: 23.0, kind: "fish stall" },
  { x1: 42.0, y1: 21.0, x2: 43.0, y2: 22.0, kind: "farm stores" },
  { x1: 44.0, y1: 21.0, x2: 45.0, y2: 22.0, kind: "farm stores" },
  { x1: 33.0, y1: 21.4, x2: 36.0, y2: 22.0, kind: "shade tree" },
  { x1: 22.0, y1: 22.0, x2: 24.0, y2: 24.0, kind: "storage shed" },
  { x1: 42.0, y1: 22.0, x2: 44.0, y2: 23.0, kind: "field fence" },
  { x1: 44.0, y1: 22.0, x2: 46.0, y2: 23.0, kind: "field fence" },
  { x1: 48.0, y1: 22.0, x2: 50.0, y2: 23.0, kind: "field fence" },
  { x1: 50.0, y1: 22.0, x2: 52.0, y2: 23.0, kind: "field fence" },
  { x1: 19.0, y1: 25.0, x2: 20.0, y2: 26.0, kind: "dockside stores" },
  { x1: 20.0, y1: 25.0, x2: 21.0, y2: 26.0, kind: "dockside stores" },
  { x1: 19.0, y1: 26.0, x2: 20.0, y2: 27.0, kind: "dockside stores" },
  { x1: 20.0, y1: 27.0, x2: 21.0, y2: 28.0, kind: "dockside stores" },
  { x1: 19.0, y1: 28.0, x2: 20.0, y2: 29.0, kind: "dockside stores" },
  { x1: 42.0, y1: 30.0, x2: 44.0, y2: 31.0, kind: "field fence" },
  { x1: 44.0, y1: 30.0, x2: 46.0, y2: 31.0, kind: "field fence" },
  { x1: 46.0, y1: 30.0, x2: 48.0, y2: 31.0, kind: "field fence" },
  { x1: 48.0, y1: 30.0, x2: 50.0, y2: 31.0, kind: "field fence" },
  { x1: 50.0, y1: 30.0, x2: 52.0, y2: 31.0, kind: "field fence" },
  { x1: 24.0, y1: 30.4, x2: 28.0, y2: 31.0, kind: "shade tree" },
];
