// GENERATED by scripts/generate-riverbend-tmj.js — do not edit by hand.
//
// One rect per stamped object, derived from the stamp itself rather than transcribed from
// it. Before Phase 53 this was a hand-maintained array in main.js and the generator wrote
// the matching rect in a trailing comment on every stamp() call; buildings carried only a
// ground-contact row, so the player could walk onto their roofs.
//
// Buildings block their whole footprint. Trees and poles block only their base row and put
// everything above it on the map's overlay layer, so the player passes behind the canopy.

export const RIVERBEND_FIELD_BLOCKS = [
  { x1: 24.0, y1: 6.0, x2: 28.0, y2: 10.0, kind: "meetinghouse" },
  { x1: 31.0, y1: 6.0, x2: 33.0, y2: 9.0, kind: "dwelling two" },
  { x1: 42.0, y1: 6.0, x2: 44.0, y2: 7.0, kind: "field fence" },
  { x1: 44.0, y1: 6.0, x2: 46.0, y2: 7.0, kind: "field fence" },
  { x1: 48.0, y1: 6.0, x2: 50.0, y2: 7.0, kind: "field fence" },
  { x1: 50.0, y1: 6.0, x2: 52.0, y2: 7.0, kind: "field fence" },
  { x1: 36.0, y1: 9.4, x2: 39.0, y2: 10.0, kind: "shade tree" },
  { x1: 34.0, y1: 11.0, x2: 36.0, y2: 14.0, kind: "dwelling three" },
  { x1: 20.0, y1: 12.0, x2: 22.0, y2: 14.0, kind: "dwelling one" },
  { x1: 28.0, y1: 12.0, x2: 30.0, y2: 14.0, kind: "well" },
  { x1: 42.0, y1: 14.0, x2: 44.0, y2: 15.0, kind: "field fence" },
  { x1: 44.0, y1: 14.0, x2: 46.0, y2: 15.0, kind: "field fence" },
  { x1: 46.0, y1: 14.0, x2: 48.0, y2: 15.0, kind: "field fence" },
  { x1: 48.0, y1: 14.0, x2: 50.0, y2: 15.0, kind: "field fence" },
  { x1: 50.0, y1: 14.0, x2: 52.0, y2: 15.0, kind: "field fence" },
  { x1: 29.0, y1: 15.0, x2: 31.0, y2: 17.0, kind: "dwelling five" },
  { x1: 33.0, y1: 15.0, x2: 35.0, y2: 17.0, kind: "hen house" },
  { x1: 21.0, y1: 16.0, x2: 23.0, y2: 20.0, kind: "dwelling four" },
  { x1: 37.0, y1: 16.0, x2: 40.0, y2: 19.0, kind: "barn" },
  { x1: 12.0, y1: 17.0, x2: 13.0, y2: 18.0, kind: "dockside stores" },
  { x1: 23.0, y1: 18.0, x2: 25.0, y2: 20.0, kind: "cold frame" },
  { x1: 14.0, y1: 19.0, x2: 15.0, y2: 20.0, kind: "dockside stores" },
  { x1: 15.0, y1: 19.0, x2: 16.0, y2: 20.0, kind: "dockside stores" },
  { x1: 18.0, y1: 19.0, x2: 20.0, y2: 21.0, kind: "wharf market stall" },
  { x1: 16.0, y1: 20.0, x2: 17.0, y2: 21.0, kind: "dockside stores" },
  { x1: 39.0, y1: 20.0, x2: 40.0, y2: 21.0, kind: "farm stores" },
  { x1: 43.0, y1: 20.0, x2: 44.0, y2: 21.0, kind: "farm stores" },
  { x1: 16.0, y1: 21.0, x2: 18.0, y2: 23.0, kind: "fish stall" },
  { x1: 42.0, y1: 21.0, x2: 43.0, y2: 22.0, kind: "farm stores" },
  { x1: 44.0, y1: 21.0, x2: 45.0, y2: 22.0, kind: "farm stores" },
  { x1: 33.0, y1: 21.4, x2: 36.0, y2: 22.0, kind: "shade tree" },
  { x1: 22.0, y1: 22.0, x2: 24.0, y2: 24.0, kind: "storage shed" },
  { x1: 42.0, y1: 22.0, x2: 44.0, y2: 23.0, kind: "field fence" },
  { x1: 44.0, y1: 22.0, x2: 46.0, y2: 23.0, kind: "field fence" },
  { x1: 48.0, y1: 22.0, x2: 50.0, y2: 23.0, kind: "field fence" },
  { x1: 50.0, y1: 22.0, x2: 52.0, y2: 23.0, kind: "field fence" },
  { x1: 19.0, y1: 25.0, x2: 20.0, y2: 26.0, kind: "dockside stores" },
  { x1: 20.0, y1: 25.0, x2: 21.0, y2: 26.0, kind: "dockside stores" },
  { x1: 19.0, y1: 26.0, x2: 20.0, y2: 27.0, kind: "dockside stores" },
  { x1: 20.0, y1: 27.0, x2: 21.0, y2: 28.0, kind: "dockside stores" },
  { x1: 19.0, y1: 28.0, x2: 20.0, y2: 29.0, kind: "dockside stores" },
  { x1: 42.0, y1: 30.0, x2: 44.0, y2: 31.0, kind: "field fence" },
  { x1: 44.0, y1: 30.0, x2: 46.0, y2: 31.0, kind: "field fence" },
  { x1: 46.0, y1: 30.0, x2: 48.0, y2: 31.0, kind: "field fence" },
  { x1: 48.0, y1: 30.0, x2: 50.0, y2: 31.0, kind: "field fence" },
  { x1: 50.0, y1: 30.0, x2: 52.0, y2: 31.0, kind: "field fence" },
  { x1: 24.0, y1: 30.4, x2: 28.0, y2: 31.0, kind: "shade tree" },
];

// The cell each building is entered from — below the centre of its front row.
// Every one of these must have road within reach; see the test named above.
export const RIVERBEND_FIELD_DOORS = [
  { col: 46, row: 5 },
  { col: 32, row: 9 },
  { col: 26, row: 10 },
  { col: 21, row: 14 },
  { col: 29, row: 14 },
  { col: 35, row: 14 },
  { col: 30, row: 17 },
  { col: 34, row: 17 },
  { col: 38, row: 19 },
  { col: 22, row: 20 },
  { col: 19, row: 21 },
  { col: 46, row: 21 },
  { col: 23, row: 24 },
];

// Every cell the road network owns — the authored trunk plus the spurs the router
// laid to each door. Read at runtime by engine/npc-routing.js, which prefers these
// cells so a routed NPC walks the road rather than cutting across the fields.
export const RIVERBEND_FIELD_ROADS = [
  [41, 5], [42, 5], [43, 5], [44, 5], [45, 5], [46, 5], [35, 6], [36, 6],
  [37, 6], [38, 6], [39, 6], [40, 6], [41, 6], [35, 7], [35, 8], [32, 9],
  [33, 9], [34, 9], [35, 9], [26, 10], [27, 10], [28, 10], [29, 10], [30, 10],
  [31, 10], [32, 10], [26, 11], [26, 12], [26, 13], [21, 14], [22, 14], [23, 14],
  [24, 14], [25, 14], [26, 14], [27, 14], [28, 14], [29, 14], [35, 14], [26, 15],
  [35, 15], [26, 16], [35, 16], [26, 17], [30, 17], [31, 17], [32, 17], [33, 17],
  [34, 17], [35, 17], [26, 18], [30, 18], [26, 19], [30, 19], [38, 19], [17, 20],
  [18, 20], [19, 20], [20, 20], [21, 20], [22, 20], [23, 20], [24, 20], [25, 20],
  [26, 20], [27, 20], [28, 20], [29, 20], [30, 20], [31, 20], [32, 20], [33, 20],
  [34, 20], [35, 20], [36, 20], [37, 20], [38, 20], [39, 20], [40, 20], [41, 20],
  [42, 20], [43, 20], [44, 20], [45, 20], [46, 20], [19, 21], [24, 21], [40, 21],
  [46, 21], [24, 22], [40, 22], [24, 23], [40, 23], [23, 24], [24, 24], [40, 24],
  [40, 25], [40, 26], [40, 27],
];
