// GENERATED by scripts/assets/pack-objects.js — do not edit by hand.
//
// Every entry here is a sprite that was repacked onto a clean 48px grid because its art in
// the source pack crossed tile boundaries and could not be stamped without clipping it or
// catching its neighbour. Coordinates are (row, col) into the derived sheet; width/height are
// measured from the pixels, not declared by hand.
//
// Regenerate with: npm run assets:pack-objects

import { tile } from "./canonical-palette.js";

/** Repacked from the source pack — see the manifest for provenance. */
export const FarmTrees = {
  treeOak: tile("derived/farm-trees.png", 0, 0, { h: 3, w: 4 }),
  treeMaple: tile("derived/farm-trees.png", 0, 4, { h: 3, w: 3 }),
  treePine: tile("derived/farm-trees.png", 0, 7, { h: 3, w: 2 }),
  treeBirch: tile("derived/farm-trees.png", 0, 9, { h: 3, w: 2 }),
  treeApple: tile("derived/farm-trees.png", 0, 11, { h: 3, w: 3 }),
  treeOrange: tile("derived/farm-trees.png", 0, 14, { h: 3, w: 2 }),
  treeCherry: tile("derived/farm-trees.png", 3, 0, { h: 3, w: 2 }),
  saplingApple: tile("derived/farm-trees.png", 3, 2, { h: 2, w: 2 }),
  saplingBlossom: tile("derived/farm-trees.png", 3, 4, { h: 2, w: 3 }),
  saplingLilac: tile("derived/farm-trees.png", 3, 7, { h: 3, w: 2 }),
  bushRose: tile("derived/farm-trees.png", 3, 9, { h: 1, w: 2 }),
  bushBerry: tile("derived/farm-trees.png", 3, 11, { h: 1, w: 2 }),
  bushFlowering: tile("derived/farm-trees.png", 3, 13, { h: 1, w: 2 }),
};

/** Repacked from the source pack — see the manifest for provenance. */
export const FarmBuildings = {
  houseRed: tile("derived/farm-buildings.png", 0, 0, { h: 2, w: 2 }),
  houseYellow: tile("derived/farm-buildings.png", 0, 2, { h: 3, w: 2 }),
  houseBlue: tile("derived/farm-buildings.png", 0, 4, { h: 3, w: 2 }),
  houseBrown: tile("derived/farm-buildings.png", 0, 6, { h: 2, w: 2 }),
  houseCream: tile("derived/farm-buildings.png", 0, 8, { h: 4, w: 2 }),
  meetinghouse: tile("derived/farm-buildings.png", 0, 10, { h: 4, w: 4 }),
  barn: tile("derived/farm-buildings.png", 4, 0, { h: 3, w: 3 }),
  statehouse: tile("derived/farm-buildings.png", 4, 3, { h: 4, w: 4 }),
  townhouseGrey: tile("derived/farm-buildings.png", 4, 7, { h: 5, w: 4 }),
  warehouse: tile("derived/farm-buildings.png", 4, 11, { h: 3, w: 3 }),
};

/** Repacked from the source pack — see the manifest for provenance. */
export const TownCivic = {
  churchSteeple: tile("derived/town-civic.png", 0, 0, { h: 4, w: 2 }),
  chapel: tile("derived/town-civic.png", 0, 2, { h: 4, w: 2 }),
};

/** Repacked from the source pack — see the manifest for provenance. */
export const InstituteArtifacts = {
  compassSmall: tile("derived/institute-artifacts.png", 0, 0, { h: 1, w: 1 }),
};

/** Repacked from the source pack — see the manifest for provenance. */
export const InstituteFurnishings = {
  stool: tile("derived/institute-furnishings.png", 0, 0, { h: 1, w: 1 }),
  stoolAlt: tile("derived/institute-furnishings.png", 0, 1, { h: 1, w: 1 }),
  lowBench: tile("derived/institute-furnishings.png", 0, 2, { h: 1, w: 3 }),
};
